FROM ilegeul/centos32:6
MAINTAINER Liviu Ionescu <ilg@livius.net>
ENTRYPOINT ["linux32"]
WORKDIR /root

RUN \
linux32 yum install -y yum-plugin-ovl; \
linux32 yum update -y; \
linux32 yum install -y \
redhat-lsb-core \
gcc-c++ \
make \
automake \
pkgconfig \
curl \
xy \
zip \
unzip \
bzip2 \
libtool \
gettext \
texinfo \
bison \
flex \
dos2unix \
patch \
perl \
which \
zlib-devel \
file \
diffutils \
cmake


CMD ["/bin/bash"]

