FROM ilegeul/centos:5-final
MAINTAINER Liviu Ionescu <ilg@livius.net>
WORKDIR /root

RUN \
yum install -y \
gcc-c++ \
make \
automake \
pkgconfig \
curl \
zip \
unzip \
bzip2 \
libtool \
gettext \
texinfo \
bison \
flex \
dos2unix \
patch \
perl \
which \
zlib-devel \
file \
diffutils


CMD ["/bin/bash"]

