FROM centos:6
MAINTAINER Liviu Ionescu <ilg@livius.net>
WORKDIR /root

RUN \
yum update -y; \
yum install -y \
redhat-lsb-core \
gcc-c++ \
make \
automake \
pkgconfig \
curl \
xy \
zip \
unzip \
bzip2 \
libtool \
gettext \
texinfo \
bison \
flex \
dos2unix \
patch \
perl \
which \
zlib-devel \
file \
diffutils


CMD ["/bin/bash"]

